name: My First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.job }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "${{ github.job }}"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "${{ github.job }}"

  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - run: echo "${{ github.job }}"

  # MyFirstJob:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "hello actions!"
      
  #     - name: Checkout
  #       uses: actions/checkout@v4.2.2

  #     - name: List all files in the repo
  #       run: |
  #         echo "The repository ${{ github.repository }} contains the following files:"
  #         tree
